<?php 

return [
    'nroContrato' => '37451-0-297',
    'beneficiarios' => [
        [
            'cpf'                => cpfValidoUnico(),
            'nome'               => 'Zemira Queiroz',
            'dataNascimento'     => '1985-05-05',
            'sexo'               => 'm',
            'cns'                => gerarCNS(),
            'grauDependencia'    => '00',
            'tipoDependencia'    => 'normal',
            'cpfTitular'         => null,
            'dataVinculoTitular' => null,
            'inicioVigencia'     => 'especificar_data',
            'dataInicioVigencia' => date('Y-m-d', strtotime('+1 day')),
            'dataAdmissao'       => '2026-01-10',
            'numeroMatricula'    => null,
            'nomeMae'            => 'mae Zemira Queiroz',
            'nomePai'            => 'pai Zemira Queiroz',
            'estadoCivil'        => 'casado',
            'nomeSocial'         => 'Nome Social',
            'generoSocial'       => 99,
            'paisNascimento'     => 32,
            'nacionalidade'      => 'Brasileira',
            'naturalidadeCidade' => 'Curitiba',
            'naturalidadeUF'     => 'PR',
            'raca'               => '1',
            'escolaridade'       => 12,
            'profissaoCBO'       => 914110,
            'emails'    => [['email' => 'zemira@email.com']],
            'enderecos' => [[
                'tipo'            => 'residencial',
                'cep'             => '80410-210',
                'correspondencia' => false,
                'faturamento'     => true,
                'notaFiscal'      => true,
                'cartaoMagnetico' => false,
                'uf'              => 'pr',
                'cidade'          => 'curitiba',
                'endereco'        => 'alameda cabral',
                'bairro'          => 'centro',
                'numero'          => '471',
                'complemento'     => 'Apto 77',
            ]],
            'telefones' => [[
                'tipo'   => 'celular',
                'classe' => 'residencial',
                'ddi'    => '',
                'ddd'    => '11',
                'numero' => '912345678',
            ]],
            'produtos' => [
                ['codigo' => '1947', 'tipo' => 'assistencial'],
                ['codigo' => '5042', 'tipo' => 'acessorio'],
            ],
        ],
    ],
];